// ── FRAMEWORK FILE ─────────────────────────────────────────────────────────
// Do not edit this file. To update CV content, edit files in cv-content/.
// ───────────────────────────────────────────────────────────────────────────

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import yaml from '@rollup/plugin-yaml'

export default defineConfig({
  plugins: [
    react(),
    yaml(),
  ],
  assetsInclude: ['**/*.ttf', '**/*.otf'],
})
