// ── FRAMEWORK FILE ─────────────────────────────────────────────────────────
// Do not edit this file. To update CV content, edit files in cv-content/.
// ───────────────────────────────────────────────────────────────────────────

import yaml from '@rollup/plugin-yaml'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [react(), yaml()],
  assetsInclude: ['**/*.ttf', '**/*.otf']
})
