// ── FRAMEWORK FILE ─────────────────────────────────────────────────────────
// Do not edit this file. To update CV content, edit files in cv-content/.
// ───────────────────────────────────────────────────────────────────────────

import { createRoot } from 'react-dom/client'
import { usePDF } from '@react-pdf/renderer'
import CVDocument from './pdf/CVDocument.jsx'
import { registerFonts } from './pdf/fonts.js'
import { THEMES } from './pdf/themes/index.js'
import {
  personal, summary, experience, achievements,
  education, competencies, referees, keywords, profilePhoto, config,
} from '../cv-content/index.js'

registerFonts('/src/fonts')

const theme = THEMES[config.theme ?? 'teal'] ?? THEMES.teal

function App() {
  const [instance] = usePDF({
    document: (
      <CVDocument
        personal={personal}
        summary={summary}
        experience={experience}
        achievements={achievements}
        education={education}
        competencies={competencies}
        referees={referees}
        keywords={keywords}
        profilePhoto={profilePhoto}
        config={config}
        theme={theme}
      />
    ),
  })

  if (instance.loading) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', background: '#c8c8c8', fontFamily: 'sans-serif', color: '#555' }}>
        Generating PDF…
      </div>
    )
  }

  if (instance.error) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', background: '#c8c8c8', fontFamily: 'sans-serif', color: '#c00', padding: '40px' }}>
        Error: {String(instance.error)}
      </div>
    )
  }

  return (
    <div style={{ background: '#c8c8c8', minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '24px 0' }}>
      <iframe
        src={/** @type {string} */ (instance.url)}
        style={{ width: '794px', minHeight: '1123px', border: 'none', boxShadow: '0 6px 32px rgba(0,0,0,0.22)' }}
        title="CV Preview"
      />
    </div>
  )
}

createRoot(/** @type {HTMLElement} */ (document.getElementById('root'))).render(<App />)
